-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 17:36:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema POO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema POO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POO` DEFAULT CHARACTER SET utf8 ;
USE `POO` ;

-- -----------------------------------------------------
-- Table `POO`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POO`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NOT NULL,
  `Sobrenome` VARCHAR(60) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `Idade` INT NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POO`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POO`.`Matricula` (
  `idMatricula` INT NOT NULL AUTO_INCREMENT,
  `AnoLetivo` INT NOT NULL,
  `Serie` BINARY(255) NOT NULL,
  `NotaPrimeiroBimestre` INT NULL,
  `NotaSegundoBimestre` INT NULL,
  `NotaTerceiroBimestre` INT NULL,
  `NotaQuartoBimestre` INT NULL,
  `Aprovado` TINYINT NULL,
  `Media` FLOAT NULL,
  PRIMARY KEY (`idMatricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POO`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POO`.`Disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(120) NOT NULL,
  `CargaHoraria` INT NOT NULL,
  `Pratica` TINYINT(1) NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POO`.`MatriculaAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POO`.`MatriculaAluno` (
  `MatriculaId` INT NOT NULL,
  `AlunoId` INT NOT NULL,
  PRIMARY KEY (`MatriculaId`, `AlunoId`),
  INDEX `fk_Matricula_has_Aluno_Aluno1_idx` (`AlunoId` ASC) VISIBLE,
  INDEX `fk_Matricula_has_Aluno_Matricula_idx` (`MatriculaId` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_has_Aluno_Matricula`
    FOREIGN KEY (`MatriculaId`)
    REFERENCES `POO`.`Matricula` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_has_Aluno_Aluno1`
    FOREIGN KEY (`AlunoId`)
    REFERENCES `POO`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POO`.`DisciplinaMatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POO`.`DisciplinaMatricula` (
  `DisciplinaId` INT NOT NULL,
  `MatriculaId` INT NOT NULL,
  PRIMARY KEY (`DisciplinaId`, `MatriculaId`),
  INDEX `fk_Disciplina_has_Matricula_Matricula1_idx` (`MatriculaId` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Matricula_Disciplina1_idx` (`DisciplinaId` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Matricula_Disciplina1`
    FOREIGN KEY (`DisciplinaId`)
    REFERENCES `POO`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Matricula_Matricula1`
    FOREIGN KEY (`MatriculaId`)
    REFERENCES `POO`.`Matricula` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
